name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: better-unreleased.csproj
      Test_Project_Path: better-unreleased.Tests/better-unreleased.Tests.csproj  

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

    - name: Create package
      run: dotnet publish -c ${{ matrix.configuration }} -r win-x64 --self-contained true -p:PublishSingleFile=true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: better-unreleased-${{ matrix.configuration }}
        path: bin/${{ matrix.configuration }}/net9.0-windows/win-x64/publish/

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/${{ matrix.configuration }}/net9.0-windows/win-x64/publish/better-unreleased.exe
          LICENSE
          README.md
        name: Release ${{ github.ref_name }}
        body: |
          Better Unreleased Music Player ${{ github.ref_name }}
          
          ## What's Changed
          * See commit history for changes
          
          ## Installation
          Download and run the `better-unreleased.exe`
          
          ## Requirements
          - Windows 7 or later
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}